vcenter_server          = "" #FQDN OR IP
username                = "" #vCenter username
password                = "" # vCenter password
insecure_connection     = "true" # Skips SSL 
host                    = "" # Suitable host
datastore               = "" #Datastore you wish the template to reside on
vm_name                 = "ubuntu2004-template" #Template Name
cluster                 = "" # Cluster Name
datacenter              = "" # Datacenter Name
folder                  = "Templates" #Template Folder
CPUs                    = 2 
RAM                     = 2000
guest_os_type           = "ubuntu64Guest"
network                 = "VM Network" # PortGroup with internet access
iso_paths               = "[NFS] ubuntu/ubuntu-20.04.1-live-server-amd64.iso" # Full ISO Path on Datastore
disk_size               = 20000 # Disk size
ssh_username            = "ubuntu" # Local Username
ssh_password            = "ubuntu" #Local password
